-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE messages (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    author_user_id integer NOT NULL,
    target_user_id integer NOT NULL,
    message text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX message_pkey ON messages(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    display_name text NOT NULL,
    email text,
    hashed_password text,
    created_at timestamp without time zone DEFAULT now(),
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX user_name_key ON users(name text_ops);


-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE message_rules (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id integer NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    tokens integer NOT NULL,
    seconds integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX message_rules_pkey ON message_rules(id int4_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE "track_events" (
    "id" integer GENERATED ALWAYS AS IDENTITY,
    "youtube_id" text NOT NULL,
    "requested_by" text NOT NULL,
    "event_type" text NOT NULL,
    "timestamp" timestamp NOT NULL,
    "guild_id" text NOT NULL,
    "title" text NOT NULL,
    "url" text NOT NULL,
    "duration" integer NOT NULL,
    "created_at" timestamp DEFAULT NOW(),
    "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id", "youtube_id")
);

-- Indices -------------------------------------------------------

CREATE INDEX idx_id_requested_by ON track_events(youtube_id, requested_by);
CREATE INDEX idx_event_type ON track_events(event_type);
