-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE messages (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    author_user_id integer NOT NULL,
    target_user_id integer NOT NULL,
    message text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX message_pkey ON messages(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    display_name text NOT NULL,
    email text,
    hashed_password text,
    created_at timestamp without time zone DEFAULT now(),
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX user_name_key ON users(name text_ops);
